/*** File generated by GenISSLib version 4.1.0: DO NOT MODIFY ***/
#ifndef __aarch64_aarch64dec_unisim__component__cxx__processor__arm__isa__arm64_HH__
#define __aarch64_aarch64dec_unisim__component__cxx__processor__arm__isa__arm64_HH__

#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
#include <cstring>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace arm { namespace isa { namespace arm64 {
typedef uint32_t CodeType;

template <	typename	ARCH>
class Operation;
template <	typename	ARCH>
class DecodeTableEntry
{
public:
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation<	ARCH> *(*decode)(CodeType, uint64_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation<	ARCH> *(*decode)(CodeType code, uint64_t addr);
};
template <	typename	ARCH>
class Decoder
{
public:
	typedef Operation<	ARCH> operation_type;
	typedef uint64_t address_type;
	typedef CodeType code_type;
	enum { alignment = 32 };

	Decoder();
	virtual ~Decoder();

	Operation<	ARCH>*NCDecode(uint64_t addr);
	Operation<	ARCH> *NCDecode(uint64_t addr, CodeType code);
	std::vector<DecodeTableEntry<	ARCH> > const& GetDecodeTable() const { return decode_table; };
	void SetLittleEndian();
	void SetBigEndian();
private:
	std::vector<DecodeTableEntry<	ARCH> > decode_table;
};

} } } } } } }

#include <iosfwd>
#include <stdint.h>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace arm { namespace isa { namespace arm64 {
template <	typename	ARCH>
class Operation
{
public:
	Operation(CodeType code, uint64_t addr, const char *name);
	virtual ~Operation();
	inline uint64_t GetAddr() const { return addr; }
	inline void SetAddr(uint64_t _addr) { this->addr = _addr; }
	inline CodeType GetEncoding() const { return encoding; }
	inline unsigned int GetLength() const { return 32; }
	inline const char *GetName() const { return name; }
	inline bool Match(uint64_t _addr, CodeType _code) const { return (this->GetEncoding() ^ _code) == 0 and GetAddr() == _addr; }
	static unsigned int const minsize = 32;
	static unsigned int const maxsize = 32;
	virtual void disasm( ARCH & cpu,
	std::ostream& sink );
	virtual void execute( ARCH & cpu );
protected:
	CodeType encoding;
	uint64_t addr;
	const char *name;
};

} } } } } } }
#endif
