/*** File generated by GenISSLib version 4.1.0: DO NOT MODIFY ***/
#ifndef __unisim_component_cxx_processor_powerpc_dba_ppc64_ppc64_unisim__component__cxx__processor__powerpc__dba__ppc64_HH__
#define __unisim_component_cxx_processor_powerpc_dba_ppc64_ppc64_unisim__component__cxx__processor__powerpc__dba__ppc64_HH__

#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
#include <cstring>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace powerpc { namespace dba { namespace ppc64 {
typedef uint32_t CodeType;

struct Operation;
struct DecodeTableEntry
{
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation *(*decode)(CodeType, uint64_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation *(*decode)(CodeType code, uint64_t addr);
};
struct Decoder
{
	typedef Operation operation_type;
	typedef uint64_t address_type;
	typedef CodeType code_type;
	enum { little_endian = 0, alignment = 32, minsize = 32, maxsize = 32 };
	Decoder();
	virtual ~Decoder();

	Operation*NCDecode(uint64_t addr);
	Operation *NCDecode(uint64_t addr, CodeType code);
	std::vector<DecodeTableEntry > const& GetDecodeTable() const { return decode_table; };
	void SetLittleEndian();
	void SetBigEndian();
private:
	std::vector<DecodeTableEntry > decode_table;
};

} } } } } } }

#include <iosfwd>
#include <inttypes.h>

namespace unisim::component::cxx::processor::powerpc::dba::arch64 { struct Arch; }

namespace unisim { namespace component { namespace cxx { namespace processor { namespace powerpc { namespace dba { namespace ppc64 {
struct Operation
{
	Operation(CodeType code, uint64_t addr, const char *name);
	virtual ~Operation();
	inline uint64_t GetAddr() const { return addr; }
	inline void SetAddr(uint64_t _addr) { this->addr = _addr; }
	inline CodeType GetEncoding() const { return encoding; }
	inline unsigned int GetLength() const { return 32; }
	inline const char *GetName() const { return name; }
	inline bool Match(uint64_t _addr, CodeType _code) const { return (this->GetEncoding() ^ _code) == 0 and GetAddr() == _addr; }
	typedef Decoder decoder_type;
	virtual void disasm( std::ostream& os );
	virtual bool execute( arch64::Arch* cpu );
protected:
	const char *name;
	uint64_t addr;
	CodeType encoding;
};

} } } } } } }
#endif
