/*** File generated by GenISSLib version 4.1.0: DO NOT MODIFY ***/
#ifndef __aarch32_top_thumb_unisim__component__cxx__processor__arm__isa__thumb_HH__
#define __aarch32_top_thumb_unisim__component__cxx__processor__arm__isa__thumb_HH__

#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
#include <cstring>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace arm { namespace isa { namespace thumb {
typedef uint32_t CodeType;

template <	typename	ARCH>
class Operation;
template <	typename	ARCH>
class DecodeTableEntry
{
public:
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation<	ARCH> *(*decode)(CodeType, uint32_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation<	ARCH> *(*decode)(CodeType code, uint32_t addr);
};
template <	typename	ARCH>
class Decoder
{
public:
	typedef Operation<	ARCH> operation_type;
	typedef uint32_t address_type;
	typedef CodeType code_type;
	enum { alignment = 16 };

	Decoder();
	virtual ~Decoder();

	Operation<	ARCH>*NCDecode(uint32_t addr);
	Operation<	ARCH> *NCDecode(uint32_t addr, CodeType code);
	std::vector<DecodeTableEntry<	ARCH> > const& GetDecodeTable() const { return decode_table; };
	void SetLittleEndian();
	void SetBigEndian();
private:
	std::vector<DecodeTableEntry<	ARCH> > decode_table;
};

} } } } } } }

#include <iosfwd>
#include <stdint.h>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace arm { namespace isa { namespace thumb {
template <	typename	ARCH>
class Operation
{
public:
	Operation(CodeType code, uint32_t addr, const char *name);
	virtual ~Operation();
	inline uint32_t GetAddr() const { return addr; }
	inline void SetAddr(uint32_t _addr) { this->addr = _addr; }
	inline CodeType GetEncoding() const { return encoding; }
	virtual unsigned int GetLength() const { return 32; }
	inline const char *GetName() const { return name; }
	inline bool Match(uint32_t _addr, CodeType _code) const { return (((this->GetEncoding() ^ _code) << (32 - this->GetLength())) & 0xffffffffUL) == 0 and GetAddr() == _addr; }
	static unsigned int const minsize = 16;
	static unsigned int const maxsize = 32;
	virtual void disasm( ARCH & cpu,
	std::ostream & buffer );
	virtual void execute( ARCH & cpu );
protected:
	CodeType encoding;
	uint32_t addr;
	const char *name;
};

} } } } } } }
#endif
