/*** File generated by GenISSLib version 3.0.2: DO NOT MODIFY ***/
#ifndef __unisim_component_cxx_processor_arm_isa_arm64_aarch64dec_unisim__component__cxx__processor__arm__isa__arm64_HH__
#define __unisim_component_cxx_processor_arm_isa_arm64_aarch64dec_unisim__component__cxx__processor__arm__isa__arm64_HH__
#ifndef __STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
#endif

#include <vector>
#include <inttypes.h>
#include <cstring>
namespace unisim { namespace component { namespace cxx { namespace processor { namespace arm { namespace isa { namespace arm64 {
typedef uint32_t CodeType;

template <
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
typename
#line 18 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
ARCH
#line 21 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
>
class Operation;
const unsigned int NUM_OPERATIONS_PER_PAGE = 4096;
template <
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
typename
#line 28 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
ARCH
#line 31 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
>
class DecodeMapPage
{
public:
	DecodeMapPage(uint64_t key);
	~DecodeMapPage();
	uint64_t key;
	DecodeMapPage *next;
	Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 43 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *operation[NUM_OPERATIONS_PER_PAGE];
};

template <
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
typename
#line 50 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
ARCH
#line 53 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
>
class DecodeTableEntry
{
public:
	DecodeTableEntry(CodeType opcode, CodeType opcode_mask, Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 61 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *(*decode)(CodeType, uint64_t));
	CodeType opcode;
	CodeType opcode_mask;
	Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 68 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *(*decode)(CodeType code, uint64_t addr);
};
const unsigned int NUM_DECODE_HASH_TABLE_ENTRIES = 4096;
template <
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
typename
#line 75 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
ARCH
#line 78 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
>
class Decoder
{
public:
	typedef Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 86 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> operation_type;

	Decoder();
	virtual ~Decoder();

	Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 95 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	>*NCDecode(uint64_t addr);
	Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 100 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *NCDecode(uint64_t addr, CodeType code);
	Operation<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 105 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *Decode(uint64_t addr, CodeType insn);
	std::vector<DecodeTableEntry<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 110 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> > const& GetDecodeTable() const { return decode_table; };
	void InvalidateDecodingCacheEntry(uint64_t addr);
	void InvalidateDecodingCache();

	void SetLittleEndian();
	void SetBigEndian();
private:
	std::vector<DecodeTableEntry<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 121 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> > decode_table;
	DecodeMapPage<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 126 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *mru_page;
	DecodeMapPage<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 131 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *decode_hash_table[NUM_DECODE_HASH_TABLE_ENTRIES];
	DecodeMapPage<
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH
#line 136 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	> *FindPage(uint64_t page_key)
#if defined(__GNUC__) && (__GNUC__ >= 3 && (__GNUC__ != 3 || __GNUC_MINOR__ != 4 || __GNUC_PATCHLEVEL__ != 6))
	__attribute__((always_inline))
#endif
	;
};

} } } } } } }
#line 46 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"

#include <iosfwd>
#include <stdint.h>
#line 149 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
namespace unisim { namespace component { namespace cxx { namespace processor { namespace arm { namespace isa { namespace arm64 {
template <
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
typename
#line 154 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 44 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
ARCH
#line 157 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
>
class Operation
{
public:
	Operation(CodeType code, uint64_t addr, const char *name);
	virtual ~Operation();
	inline uint64_t GetAddr() const { return addr; }
	inline void SetAddr(uint64_t _addr) { this->addr = _addr; }
	inline CodeType GetEncoding() const { return encoding; }
	inline unsigned int GetLength() const { return 32; }
	inline const char *GetName() const { return name; }
	static unsigned int const minsize = 32;
	static unsigned int const maxsize = 32;
	virtual
#line 67 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	void
#line 174 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	disasm(
#line 67 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH &
#line 178 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 67 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	cpu
#line 181 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	,
#line 67 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	std::ostream&
#line 185 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 67 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	sink
#line 188 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	);
	virtual
#line 65 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	void
#line 193 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	execute(
#line 65 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	ARCH &
#line 197 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
#line 65 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.isa"
	cpu
#line 200 "unisim/component/cxx/processor/arm/isa/arm64/aarch64dec.hh"
	);
protected:
	CodeType encoding;
	uint64_t addr;
	const char *name;
};

} } } } } } }
#endif
